### ISSUE TITLE
Accessing Variables from protected array in object response

### ISSUE THREAD

**Issue by Nganyu** [maviance/smobilpay-php#3]
Hi, Good day. Trying to setup your cashout/Cashin Api and i am stucked at this point. When i call cashoutget, the server response has the format

Array
(
    [0] => Maviance\S3PApiClient\Model\Cashout Object
        (
            [container:protected] => Array
                (
                    [serviceid] => 20053
                    [merchant] => MTNMOMO
                    [payItemId] => S-112-949-MTNMOMO-20053-200050001-1
                    [payItemDescr] => 
                    [amountType] => CUSTOM
                    [localCur] => XAF
                    [name] => CASH-OUT
                    [amountLocalCur] => 
                    [description] => Cash out a custom amount
                    [optStrg] => 
                    [optNmb] => 
                )

        )

)

Do you guys have a method in one of your classes that i can call to access these a variables. 
Thanks.

**Comment by camoo** [comment]
```php
/** @var \Maviance\S3PApiClient\Model\Cashout $cashout */
$cashout = $response[0];
```

then `$cashout` is the object you need
