### ISSUE TITLE
Service\HealthcheckApi not found

### ISSUE THREAD

**Issue by benorine** [maviance/smobilpay-php#5]
I tried the `ping` route but got an error 
`Class "App\Http\Controllers\Maviance\S3PApiClient\Service\HealthcheckApi" not found` 

Steps to reproduce 
1. Adds dependency as directed 
```
"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.8",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "maviance/smobilpay-php": "*"
    },
```
2. Creates a function `ping` in my controller 
```
/// //
 private string $xApiVersion = "3.0.0"; // string | api version info
///
///

 public function ping()
    {
        $apiInstance = new Maviance\S3PApiClient\Service\HealthcheckApi();

        try {
            $result = $apiInstance->pingGet($this->xApiVersion);
            return response()->json([
                'data' => $result,
            ]);
            //print_r($result);
        } catch (Exception $e) {
            return response()->json([
                'message' => 'Exception when calling HealthcheckApi->pingGet: ', $e->getMessage(), PHP_EOL
            ]);
            // echo 'Exception when calling HealthcheckApi->pingGet: ', $e->getMessage(), PHP_EOL;
        }
    }
```

3.  Adds the routes in my `routes/api.php`
`Route::get('ping', [MobilePaymentController::class, 'ping'])->name('ping');`

4. Calls the route on the browser `http://127.0.0.1:8000/api/ping`
5. Error 
```
Error

Class "App\Http\Controllers\Maviance\S3PApiClient\Service\HealthcheckApi" not found
```

**Comment by ntja** [comment]
Hello Benorine,

There is an issue with your namespace. You are not properly calling the class. To fix it you can do  the following (either 1 or 2):

1. Add forward slash in the class path: **$apiInstance = new \Maviance\S3PApiClient\Service\HealthcheckApi();**
2. Import the class at the top of your controller : **use Maviance\S3PApiClient\Service\HealthcheckApi;**

**Comment by benorine** [comment]
Thanks for the help @ntja. 
The issue is now resolved.
